# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Masato Kubotera
title: Robot Creator
email: masatokubotera06@yahoo.co.jp
website: https://masatokubotera.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: CreateRoboCup
github_username:  MasatoKubotera
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Masato Kubotera and I am a robot creator, I have been developing autonomous robots since I was 11 years old through RoboCup.

content:

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CIT Brains
        link: http://www.cit-brains.net/
        # link_text: boringcompany.com
        sub_title: Hardware Engineer
        caption: August 2019 - Present
        quote: >
            The research team developing the fully autonomous humanoid robot to compete in the RoboCup Humanoid League.
        description: | # this will include new lines to allow paragraphs
            CIT Brains is a department project of the Dept. of Advanced Robotics at Chiba Institute of Technology, and has been competing in the RoboCup Humanoid League since 2006.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Chiba Institute of Technology
        caption: 2019 - Present
        sub_title: Dept. of Advanced Robotics
        description: | # this will include new lines to allow paragraphs
          The Department of Advanced Robotics at Chiba Institute of Technology is refining our knowledge and skills of creating things as we pursue cutting edge robotic research and development.

          I am developing an *open Hardware Platform Humanoid Robot "SUSTAINA-OP"* for RoboCup Humanoid League.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in robotics and hardware engineering some of my other interests and hobbies are:
      - Education

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
